# Site settings
title: Tajdid Rahman
email: tajdidrahman@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: tajdidr
github_username:  tajdid
avatar: https://pbs.twimg.com/profile_images/572076793079664640/gz4KhtuS_400x400.jpeg

# Build settings
markdown: kramdown
permalink: pretty
